services:
  main-server:
    image: pypiserver/pypiserver:latest
    ports:
      - 8080:8080
    volumes:
      - type: volume
        source: pypi-main-server
        target: /data/packages
      - type: bind
        source: ./.htpasswd
        target: /data/.htpasswd
    command: run -P file:/data/.htpasswd -a update /data/packages
    restart: always

  dev-server:
    image: pypiserver/pypiserver:latest
    ports:
      - 8081:8080
    volumes:
      - type: volume
        source: pypi-dev-server
        target: /data/packages
      - type: bind
        source: ./.htpasswd
        target: /data/.htpasswd
    command: run -P file:/data/.htpasswd -a update /data/packages
    restart: always

volumes:
  pypi-main-server:
  pypi-dev-server: